room_security:
    resource: "@RoomSecurityBundle/Resources/config/routing.yml"
    prefix:   /

room_hotel:
    resource: "@RoomHotelBundle/Resources/config/routing.yml"
    prefix:   /

room_booking_engine:
    resource: "@RoomBookingEngineBundle/Resources/config/routing.yml"
    prefix:   /

room_site_management:
    resource: "@RoomSiteManagementBundle/Resources/config/routing.yml"
    prefix:   /
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile
_security_check:
    pattern:  /{_locale}/login_check
_security_logout:
    pattern:  /{_locale}/logout
fos_facebook_channel:
    resource: "@FOSFacebookBundle/Resources/config/routing.xml"

