room_booking_engine_homepage:
    path:     /
    defaults: { _controller: RoomBookingEngineBundle:Booking:index }
room_booking_engine_search:
    path:     /search
    defaults: { _controller: RoomBookingEngineBundle:Booking:search }
room_booking_engine_add_room:
    path:     /add-room
    defaults: { _controller: RoomBookingEngineBundle:Booking:addRoom }
room_booking_engine_add_adults:
    path:     /add-adults
    defaults: { _controller: RoomBookingEngineBundle:Booking:addAdults }
room_booking_engine_add_childs:
    path:     /add-child
    defaults: { _controller: RoomBookingEngineBundle:Booking:addChilds }
room_booking_engine_update_room:
    path:     /update-room
    defaults: { _controller: RoomBookingEngineBundle:Booking:updateRomms }
room_booking_engine_filter:
    path:     /filter
    defaults: { _controller: RoomBookingEngineBundle:Booking:filter }
room_booking_engine_view_more:
    path:     /view-more/{id}
    defaults: { _controller: RoomBookingEngineBundle:Booking:viewMore }
room_booking_engine_confrim:
    path:     /confirm
    defaults: { _controller: RoomBookingEngineBundle:Booking:confirm }
room_booking_engine_booking:
    path:     /booking
    defaults: { _controller: RoomBookingEngineBundle:Booking:booking }
room_booking_engine_booking_submit:
    path:     /booking-submit
    defaults: { _controller: RoomBookingEngineBundle:Booking:bookingSubmit }
room_booking_engine_success:
    path:     /booking-success
    defaults: { _controller: RoomBookingEngineBundle:Booking:success }

room_booking_engine_pay_online:
    path:     /{bookingId}/pay-online
    defaults: { _controller: RoomBookingEngineBundle:Booking:payOnline }

room_booking_engine_apply_coupon:
    path:     /apply-coupon
    defaults: { _controller: RoomBookingEngineBundle:Booking:applyCoupon }

room_booking_engine_admin_apply_coupon:
    path:     /admin-apply
    defaults: { _controller: RoomBookingEngineBundle:Booking:adminapplyCoupon }

room_booking_service_details_apartment:
    path:     /service-detail/{url}
    defaults: { _controller: RoomBookingEngineBundle:Booking:serviceDetail }

room_booking_engine_payment_payu:
    path:     /payu
    defaults: { _controller: RoomBookingEngineBundle:Booking:payu }

room_booking_engine_payment_confirmation:
    path:     /paymentconfirmation
    defaults: { _controller: RoomBookingEngineBundle:Booking:paymentconfirmation }

room_booking_engine_customer_payment_confirmation:
    path:     /customerpaymentconfirmation
    defaults: { _controller: RoomBookingEngineBundle:Booking:adminpaymentSuccess }

room_booking_engine_payment_Details:
    path:     /paymentDetailsAction
    defaults: { _controller: RoomBookingEngineBundle:Booking:paymentDetailsAction }

remove_trailing_slash:
    path: /{url}
    defaults: { _controller: RoomBookingEngineBundle:Booking:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]
    