services:
#    room_booking_engine.example:
#        class: Room\BookingEngineBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
     mail.services:
        class: Room\BookingEngineBundle\Service\MailServices
        arguments: ["@doctrine.orm.entity_manager",'@service_container', '@session']